language: python

install:
- pip install -r requirements.txt

script:
- py.test --cov-report term --cov=app/test/

env:
- CODECOV_TOKEN=cd757494-68f8-46ab-a2b3-41d9d8496aed

after_success:
- codecov 

